# Generated by Django 4.2.13 on 2024-12-12 12:09

import account.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.CharField(
                        auto_created=True,
                        default=utils.models.get_default_uuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=32, unique=True, verbose_name="用户名"),
                ),
                (
                    "cn_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="中文名称"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, unique=True, verbose_name="手机号"),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="邮箱地址"),
                ),
                (
                    "wxid",
                    models.CharField(max_length=32, unique=True, verbose_name="微信号"),
                ),
                ("is_staff", models.BooleanField(default=True, verbose_name="工作人员")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "1 - 🙍\u200d♂️ 用户模型",
                "verbose_name_plural": "1 - 🙍\u200d♂️ 用户模型",
                "ordering": ["-created"],
            },
            managers=[
                ("objects", account.models.EmailUserManager()),
            ],
        ),
    ]
