# Generated by Django 4.2.13 on 2024-12-12 12:09

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.CharField(
                        auto_created=True,
                        default=utils.models.get_default_uuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "title",
                    models.CharField(
                        db_comment="用户自定义的", max_length=50, verbose_name="数据源"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="标示符"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Prometheus", "Prometheus"),
                            ("Zabbix", "Zabbix"),
                            ("Dem", "Dem"),
                            ("CCloud", "CCloud"),
                        ],
                        max_length=32,
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "1 - \U0001fae7 数据源管理",
                "verbose_name_plural": "1 - \U0001fae7 数据源管理",
            },
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        auto_created=True,
                        default=utils.models.get_default_uuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        auto_created=True,
                        default=utils.models.get_default_uuid,
                        max_length=32,
                        unique=True,
                        verbose_name="秘钥 Token",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(blank=True, null=True, verbose_name="start"),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="end"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "title",
                    models.CharField(
                        db_comment="秘钥名称", max_length=50, verbose_name="秘钥名称"
                    ),
                ),
                (
                    "ds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.datasource",
                        verbose_name="数据源",
                    ),
                ),
            ],
            options={
                "verbose_name": "2 - 🔑 密钥认证",
                "verbose_name_plural": "2 - 🔑 密钥认证",
            },
        ),
    ]
